### ISSUE TITLE
how to use bypass.c 

### ISSUE THREAD

**Issue by Natto97** [averagesecurityguy/scripts#9]

**Comment by averagesecurityguy** [comment]
**_I wrote bypass.c 8 years ago and have no idea if it will still work because there have been many changes to Metasploit since then._**

Bypass.c is stager for Metasploit payloads and I wrote it because the Metasploit stager was often caught by AV. At the time I wrote it you would need to do the following:

1. Setup a multi/handler on Metasploit.
2. Modify the IP and Port constants to point to your Metasploit multi/handler.
3. Compile the bypass.c code for your target machine.
4. Run the code on your target machine.

Bypass would reach out to Metasploit, and receive bytes from the server. The first four bytes were the payload size and the rest were the payload. Bypass would then allocate new RWX memory, copy the payload into that memory and execute it.
